#!/usr/bin/env python
'''
In spite of the grandiose name of this script, all really does is use
the utility `od` to format a hex dump of an .fcm file, but to do something
`od` can't which is to convert byte addresses to halfword addresses.


'''

import sys
import os
import subprocess

try:
    command = ["od", "-A", "x", "-t", "x2", "--endian=big", sys.argv[1]]
    result = subprocess.run(command, capture_output = True, text = True, check = True)
except:
    print("Usage:")
    print("\tfcmViewer FILE.fcm")
    print("\t\tor")
    print("\tfcmViewer FILE.fcm | less")
    print("\t\tetc.")
    print("Note: Requires the `od` utility.")
    os._exit(1)

for line in result.stdout.split("\n"):
    try:
        fields = line.split()
        if len(fields[0]) != 6:
            print(f"{line}")
            continue
        fields[0] = "%06x" % (int(fields[0], 16) // 2)
        print(" ".join(fields))
    except:
        print(f"{line}")
